In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/IRIS.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [11]:
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [12]:
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].to_numpy()
y = df[['species']]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
encode = LabelEncoder()
y = encode.fit_transform(y)
y

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
classifier = KNeighborsClassifier(n_neighbors=5, algorithm='kd_tree')
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='kd_tree')

In [15]:
y_test

array([2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 1, 0, 0, 1, 0, 2, 0, 1, 2, 1, 2, 2,
       0, 1, 1, 1, 1, 0, 2, 0])

In [16]:
X_test

array([[ 0.79566902, -0.1249576 ,  0.81962435,  1.05353673],
       [-1.02184904,  0.33784833, -1.45500381, -1.31297673],
       [-0.05250608, -0.8191665 ,  0.76275864,  0.92206376],
       [ 1.64384411,  0.33784833,  1.27454998,  0.79059079],
       [-0.05250608,  2.18907205, -1.45500381, -1.31297673],
       [ 0.06866179,  0.33784833,  0.59216153,  0.79059079],
       [ 1.03800476,  0.10644536,  0.36469871,  0.26469891],
       [-0.90068117,  1.72626612, -1.05694388, -1.05003079],
       [ 2.24968346, -0.1249576 ,  1.33141568,  1.44795564],
       [-0.17367395, -0.58776353,  0.1941016 ,  0.13322594],
       [-0.29484182, -0.35636057, -0.09022692,  0.13322594],
       [-0.41600969,  1.03205722, -1.39813811, -1.31297673],
       [-1.38535265,  0.33784833, -1.227541  , -1.31297673],
       [ 0.55333328, -1.74477836,  0.36469871,  0.13322594],
       [-1.14301691,  0.10644536, -1.2844067 , -1.4444497 ],
       [ 0.4321654 ,  0.80065426,  0.93335575,  1.44795564],
       [-0.90068117,  1.

In [19]:
print(classifier.predict(X_test))
print(y_test)

[2 0 2 2 0 2 1 0 2 1 1 0 0 1 0 2 0 1 2 1 2 2 0 1 1 1 1 0 1 0]
[2 0 2 2 0 1 1 0 2 1 1 0 0 1 0 2 0 1 2 1 2 2 0 1 1 1 1 0 2 0]


In [21]:
classifier.score(X_test, y_test)

0.9333333333333333